### ISSUE TITLE
deal with speakers

### ISSUE THREAD

**Issue by q9f** [blockchainweek/explore#2]
I'm not sure if we need this, but it seems there is a hacky way for each event to scrape speakers and aggregate them in the backend.

https://github.com/prgblockweek/prague-blockchain-week/blob/main/data/23/events/dotprague/_sync.js

_To be discussed._

**Comment by kuzdogan** [comment]
IMO the website should contain minimal information. If anyone wants to know about the speakers they can go to each event's website. The number of speakers in last year's PBW is immense and does not really help in any sense https://explore.prgblockweek.com/23

**Comment by q9f** [comment]
yes, franzi also said that. I already removed the speaker section. 👍🏼
